### ISSUE TITLE
`yarn build` Sometimes Failing - Corrupt Files

### ISSUE THREAD

**Issue by SummerWorkerECCC** [e3c-summer-worker/components#38]
`yarn build` sometimes fails when building on CI, most likely due to multiple elm processes running at the same time. It's interesting as this only happens occasionally.

Examples:
- Failure: https://github.com/e3c-summer-worker/components/runs/4414444984?check_suite_focus=true
- Success: https://github.com/e3c-summer-worker/components/runs/4414314973?check_suite_focus=true

**Comment by SummerWorkerECCC** [comment]
Looks like this is still happening...

**Comment by joshuanianji** [comment]
Looks like [Snowpack Elm fixes this problem](https://github.com/marc136/snowpack-plugin-elm/commit/d8b2e37)! Will move to use Snowpack then.

**Comment by SummerWorkerECCC** [comment]
On second thought, looks like Snowpack [does not support monorepos](https://github.com/withastro/snowpack/issues/429#issuecomment-647041937). It would be weird to try to squeeze in Snowpack with Yarn 3 pnp while the other components are using webpack anyway. 

I keep getting `Error: EROFS: read-only filesystem, mkdir '/node_modules/snowpack-plugin-elm/.temp'` when trying to run Snowpack. Maybe I should just put the Navigation to its own directory?

**Comment by SummerWorkerECCC** [comment]
Oops didn't realize the PR links were automatic. Ignore the notif pollution above.

**Comment by SummerWorkerECCC** [comment]
For posterity's sake, here are some screenshots of the GIthub actions before and after the fix (using the workflow `nav-test-build.yml`.

Before: (Some builds will fail, very randomized)
<img width="1680" alt="Screen Shot 2021-12-13 at 9 16 07 AM" src="https://user-images.githubusercontent.com/86326466/145848369-8dd27d16-dea7-4d78-aa25-d26f7ca616ae.png">

After: (All builds pass)
<img width="1680" alt="Screen Shot 2021-12-13 at 9 16 41 AM" src="https://user-images.githubusercontent.com/86326466/145848404-9053c903-1199-4715-9245-682eccf93b3d.png">
